### ISSUE TITLE
Release candidate fails to init

### ISSUE THREAD

**Issue by c4t3l** [c4t3l/vimde#7]
It looks like the copy_configs function can't find the source file since it changed locations (from specfile -- this was changed to `/etc/vimde/vimderc|tmuxderc`)

```
[rcallicotte@zuul-master-test vimde]$ vimde --init
Traceback (most recent call last):
  File "/usr/bin/vimde", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/vimde/cli.py", line 29, in main
    utils.init_environment()
  File "/usr/lib/python3.12/site-packages/vimde/utils.py", line 50, in init_environment
    if copy_configs():
       ^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/vimde/utils.py", line 66, in copy_configs
    shutil.copy(global_vimderc, local_vimderc)
  File "/usr/lib64/python3.12/shutil.py", line 435, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib64/python3.12/shutil.py", line 260, in copyfile
    with open(src, 'rb') as fsrc:
         ^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/etc/vimdevimderc'
```

**Comment by c4t3l** [comment]
Config files will have names changed to match what is in #5 (`vimde.conf|tmuxde.conf`)

**Comment by c4t3l** [comment]
Fixed in f8ed30d92767f00f8067aef4bb08b823811ba4d4.
